# Generated by Django 5.1.3 on 2024-12-05 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_id_showposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d4993de-dc39-46f0-9e01-d20a0c0bd657'), editable=False, primary_key=True, serialize=False),
        ),
    ]
