# Generated by Django 5.1.3 on 2024-12-05 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showposts',
            options={'verbose_name': 'Show Post', 'verbose_name_plural': 'Show Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b1df003f-7321-47ba-ae14-2d62d772e818'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='showposts',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
